// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACtiqlVXSvidy23-jdyPUoxCbY3wn0t50',
    appId: '1:835824825157:android:d6cfd4625cae6db482442c',
    messagingSenderId: '835824825157',
    projectId: 'sdl-v2',
    databaseURL: 'https://sdl-v2-default-rtdb.firebaseio.com',
    storageBucket: 'sdl-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7MslYFRc7hI1N5pjTM4nXiR7WBtwbxAc',
    appId: '1:835824825157:ios:ff3658858707a20782442c',
    messagingSenderId: '835824825157',
    projectId: 'sdl-v2',
    databaseURL: 'https://sdl-v2-default-rtdb.firebaseio.com',
    storageBucket: 'sdl-v2.appspot.com',
    iosClientId: '835824825157-91mrua7m2hs8ntpoqjvrkgk2c8s1b3bb.apps.googleusercontent.com',
    iosBundleId: 'com.example.sdlV2',
  );
}
